// <auto-generated />
using System;
using FamilyFastFoodSimpleApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyFastFoodSimpleApi.Migrations
{
    [DbContext(typeof(FamilyFastFoodSimpleApiContext))]
    [Migration("20230807092653_hello")]
    partial class hello
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FamilyFastFoodSimpleApi.DataModels.Categories", b =>
                {
                    b.Property<int>("CategoriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriesId"));

                    b.Property<string>("CategoriesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriesId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FamilyFastFoodSimpleApi.DataModels.Cuisines", b =>
                {
                    b.Property<int>("CuisinesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CuisinesId"));

                    b.Property<string>("CuisinesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CuisinesId");

                    b.ToTable("Cuisines");
                });

            modelBuilder.Entity("FamilyFastFoodSimpleApi.DataModels.Ingredients", b =>
                {
                    b.Property<int>("IngredientsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientsID"));

                    b.Property<double?>("Calcium")
                        .HasColumnType("float");

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<double?>("Cholesterol")
                        .HasColumnType("float");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<double?>("DietaryFiber")
                        .HasColumnType("float");

                    b.Property<string>("IngredientsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Iron")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Protein")
                        .HasColumnType("float");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<double?>("SaturatedFat")
                        .HasColumnType("float");

                    b.Property<double?>("Sodium")
                        .HasColumnType("float");

                    b.Property<double?>("Sugars")
                        .HasColumnType("float");

                    b.Property<double?>("TotalCarbohydrates")
                        .HasColumnType("float");

                    b.Property<double?>("TotalFat")
                        .HasColumnType("float");

                    b.Property<double?>("TransFat")
                        .HasColumnType("float");

                    b.Property<double?>("VitaminA")
                        .HasColumnType("float");

                    b.Property<double?>("VitaminC")
                        .HasColumnType("float");

                    b.Property<double?>("VolumeMl")
                        .HasColumnType("float");

                    b.Property<double?>("WeightGram")
                        .HasColumnType("float");

                    b.Property<string>("WhereToGet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredientsID");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("FamilyFastFoodSimpleApi.DataModels.Recipes", b =>
                {
                    b.Property<int>("RecipesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipesID"));

                    b.Property<int?>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int?>("CuisinesId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IngredientsID1")
                        .HasColumnType("int");

                    b.Property<int?>("IngredientsID2")
                        .HasColumnType("int");

                    b.Property<int?>("IngredientsID3")
                        .HasColumnType("int");

                    b.Property<int?>("IngredientsID4")
                        .HasColumnType("int");

                    b.Property<int?>("IngredientsID5")
                        .HasColumnType("int");

                    b.Property<string>("PrepTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipesTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServingSize")
                        .HasColumnType("int");

                    b.Property<string>("Stepbystep1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stepbystep2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stepbystep3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stepbystep4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stepbystep5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stepbystep6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TagsId")
                        .HasColumnType("int");

                    b.Property<string>("TotalTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecipesID");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("FamilyFastFoodSimpleApi.DataModels.Tags", b =>
                {
                    b.Property<int>("TagsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagsId"));

                    b.Property<string>("TagsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagsId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("FamilyFastFoodSimpleApi.DataModels.UserLogins", b =>
                {
                    b.Property<int>("UserLoginsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserLoginsId"));

                    b.Property<int?>("UserCaloriesConsumed")
                        .HasColumnType("int");

                    b.Property<int?>("UserCaloriesGoal")
                        .HasColumnType("int");

                    b.Property<string>("UserLoginsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLoginsPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserLoginsId");

                    b.ToTable("UserLogins");
                });
#pragma warning restore 612, 618
        }
    }
}
